---
title: "Estimate the origin region of cells"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r load libraries}
library(here)
library(Seurat)
library(tidyverse)
library(patchwork)
library(SingleR)

# load custom functions
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```

## Introduction
Previous studies performed bulk RNA seq of the different midgut sections. We can use that expression profile, to try and predict where our cells are coming from.

```{r}
# load in our data
notch <- readRDS(here("output", "notchKO_seurat_integrated_annotated_high_res_cellcycle.rds"))

# load in data from https://www.sciencedirect.com/science/article/pii/S2211124715006075?via%3Dihub
# Downloaded the "Summary Table" from http://flygutseq.buchonlab.com/resources
# and then did gene name mapping
region_expression_dutta <- data.table::fread(here::here("raw_data", "region_specific_expression_dutta.tsv"), data.table = F)

# remove all genes that do not occur in our dataset
region_expression_dutta <- region_expression_dutta %>%
    dplyr::filter(symbol %in% rownames(notch))
```


```{r}
##################
# SINGLER FOR EC #
##################
bulk_expression_matrix_ec <- region_expression_dutta[, grep("EC", colnames(region_expression_dutta))] %>%
    as.matrix()

rownames(bulk_expression_matrix_ec) <- region_expression_dutta$symbol

ec_region_prediction_dutta <- SingleR(
    test = notch@assays$RNA@data,
    ref = bulk_expression_matrix_ec,
    labels = c("R1", "R2", "R3", "R4", "R5")
)

# add the prediction to the appropriate celltypes
notch@meta.data$region_prediction <- case_when(
    notch@meta.data$celltype_manual %in% c("aEC", "pEC", "Copper", "mEC", "LFC") ~ ec_region_prediction_dutta$pruned.labels,
    T ~ "region prediction not available"
)



##################
# SINGLER FOR EB #
##################
bulk_expression_matrix_eb <- region_expression_dutta[, grep("EB", colnames(region_expression_dutta))] %>%
    as.matrix()

rownames(bulk_expression_matrix_eb) <- region_expression_dutta$symbol

eb_region_prediction_dutta <- SingleR(
    test = notch@assays$RNA@data,
    ref = bulk_expression_matrix_eb,
    labels = c("R1", "R2", "R3", "R4", "R5")
)

notch@meta.data$region_prediction <- case_when(
    notch@meta.data$celltype_manual %in% c("EB", "ISC", "dEC", "daEC") ~ eb_region_prediction_dutta$pruned.labels,
    T ~ notch@meta.data$region_prediction
)



##################
# SINGLER FOR EE #
##################
bulk_expression_matrix_ee <- region_expression_dutta[, grep("EE", colnames(region_expression_dutta))] %>%
    as.matrix()

rownames(bulk_expression_matrix_ee) <- region_expression_dutta$symbol

ee_region_prediction_dutta <- SingleR(
    test = notch@assays$RNA@data,
    ref = bulk_expression_matrix_ee,
    labels = c("R1", "R2", "R3", "R4", "R5")
)


notch@meta.data$region_prediction <- case_when(
    notch@meta.data$celltype_manual %in% c("EE") ~ ee_region_prediction_dutta$pruned.labels,
    T ~ notch@meta.data$region_prediction
)
saveRDS(notch, here("output", "notchKO_seurat_integrated_annotated_high_res_cellcycle_region.rds"))
DimPlot(notch, group.by = "region_prediction")
```


```{r}
sessionInfo()
```




















