---
title: "Figure 2 Show Cph Expression along lineage 4"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)
library(ComplexHeatmap)
library(circlize)
library(tradeSeq)
library(SingleCellExperiment)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


## Introduction
This script is to check the expression of certain genes of interest.

```{r load libraries}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)
library(condiments)
library(slingshot)

# source plotting theme
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```



```{r}
seurat <- readRDS(here("output", "seuratKO_slingshot_object_integrated.rds"))

seurat[["pca_mod"]] <- CreateDimReducObject(
    embeddings = Embeddings(seurat, reduction = "pca") * -1,
    key = "PCAmod_",
    assay = "integrated"
)
smoothers_data <- readRDS(here("output", "plotSmoothers_data.rds"))

# see the script 9_trajectory_inference/trajectory_inference_condiments.Rmd why this is okay to do
slingshot_individual <- readRDS(here("output", "slingshot_individual_fit.rds"))
slingshot_individual$condition_id <- names(slingshot_individual)
slingshot_individual$mapping <- matrix(rep(1:4, each = 2), nrow = 4, ncol = 2, byrow = TRUE)
slingshot_merged <- do.call(merge_sds, slingshot_individual)


plot_curves <- function(gene) {
    plots <- lapply(c("ctrl", "notch"), function(condition) {
        upper_limit <- FetchData(seurat, c(gene))[, 1] %>% max()

        sds_cond <- slingshot_individual[[condition]]
        data <- FetchData(seurat, c("PCAmod_1", "PCAmod_2", "perturbation", gene)) %>%
            filter(perturbation == condition) %>%
            arrange(!!sym(gene))

        p <- ggplot(data, aes(PCAmod_1, PCAmod_2, color = !!sym(gene))) +
            geom_point(size = 0.08, shape = 19, stroke = 0.2, alpha = 0.8) +
            scale_color_gradient(low = "grey", high = "darkred", limits = c(0, upper_limit), name = str_interp("${gene}\nexpression")) +
            small_axis("PC ", arrow_length = 19) +
            geom_path(data = slingCurves(sds_cond)[[4]]$s[slingCurves(sds_cond)[[4]]$ord, ] %>%
                as.data.frame(), aes(x = PCAmod_1, y = PCAmod_2), color = "black", linewidth = 0.3) +
            scale_y_reverse() +
            ggtitle(condition) +
            theme(
                legend.title = element_text(size = 10),
                legend.text = element_text(size = 9),
                legend.key.size = unit(0.8, "lines")
            )
        return(p)
    })
    return(wrap_plots(plots, ncol = 1) + plot_layout(guides = "collect"))
}

# plot Cph
p <- plot_curves("CG9650")

ggsave(
    plot = p,
    width = 2.5,
    height = 3,
    filename = here("plots", "main", "Fig2_Cph_PCA_lineage_expr.pdf"),
    scale = 1.5
)
```


```{r}
sessionInfo()
```





