---
title: "Recluster the EE population to resolve finer substractures"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```

## Introduction

THE SUBCLUSTERING DOES NOT WORK BECAUSE THERE SIMPLY ARE NOT ENOUGH CELLS

We select all cells that were assigned as EEs and recluster them to identify subtypes that are known in the literature. 

```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(circlize)
library(ComplexHeatmap)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```

```{r}
# load the annotated seurat object
notchRNAi <- readRDS(here("output", "notchRNAi_seurat_TX47_annotated.rds"))

# select EE cells
DefaultAssay(notchRNAi) <- "RNA"
EE_notchRNAi <- DietSeurat(notchRNAi, assays = "RNA")[, notchRNAi$celltype_manual == "EE"]
EE_notchRNAi@meta.data <- EE_notchRNAi@meta.data %>%
    dplyr::select(-contains("RNA_snn"))

# rerun clustering after the subsetting
EE_notchRNAi <- run_seurat_steps(EE_notchRNAi, include_norm = T, include_leiden = F, include_louvain = T)
```


```{r}
# based on literature and flygut atlas
marker_table <- data.frame(
    gene = c(
        "Tk", "Dh31", "NPF",
        "AstA", "AstC", "CCHa1",
        "CCHa2", "Orcokinin",
        "esg", "hdc", "Dl"
    ),
    celltype = c(
        "gut     \nhormones", "gut     \nhormones", "gut     \nhormones",
        "gut     \nhormones", "gut     \nhormones", "gut     \nhormones",
        "gut     \nhormones", "gut     \nhormones",
        "stem-cell\nmarker", "stem-cell\nmarker", "stem-cell\nmarker"
    )
)

marker_table$celltype <- factor(marker_table$celltype, levels = unique(marker_table$celltype))

# draw heatmap
heatmap_notchRNAi <- marker_heatmap(
    seurat = EE_notchRNAi,
    markers = marker_table$gene,
    celltype = marker_table$celltype,
    group.by = "RNA_snn_res.0.5",
    cap_value = 3
)

# assign subtypes based on this heatmap:
EE_notchRNAi$EE_subtype <- case_when(
    EE_notchRNAi$RNA_snn_res.0.5 == 0 ~ "EEP",
    EE_notchRNAi$RNA_snn_res.0.5 == 1 ~ "AstC-EE",
    EE_notchRNAi$RNA_snn_res.0.5 == 2 ~ "EEP", # not as obvious but using or notch knockout data this is also the predicted label
    EE_notchRNAi$RNA_snn_res.0.5 == 3 ~ "EEP",
    EE_notchRNAi$RNA_snn_res.0.5 == 4 ~ "classIII-EE",
    EE_notchRNAi$RNA_snn_res.0.5 == 5 ~ "EEP",
    EE_notchRNAi$RNA_snn_res.0.5 == 6 ~ "AstC-EE"
)


DimPlot(EE_notchRNAi, group.by = "EE_subtype", label = T)
```


### Now add this information back to the "whole" seurat object
```{r}
notchRNAi@meta.data$Barcode_unique <- Cells(notchRNAi)

notchRNAi@meta.data <- notchRNAi@meta.data %>%
    left_join(., EE_notchRNAi@meta.data %>%
        rownames_to_column("Barcode_unique") %>%
        select(Barcode_unique, high_res_annotation = EE_subtype),
    by = "Barcode_unique"
    )
rownames(notchRNAi@meta.data) <- notchRNAi$Barcode_unique

notchRNAi@meta.data$high_res_annotation <- case_when(
    is.na(notchRNAi@meta.data$high_res_annotation) ~ notchRNAi@meta.data$celltype_manual,
    T ~ notchRNAi@meta.data$high_res_annotation
)

saveRDS(notchRNAi, here("output", "notchRNAi_seurat_TX47_annotated_high_res.rds"))
```


```{r}
sessionInfo()
```
















