---
title: "Figure 2 Show Cph Expression in EEPs as Violine plot"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```



```{r}
# load progenitor population with MELD labels
progenitors <- readRDS(here("output", "Ctrl_NotchKO_progenitors_integrated_meld.rds"))

# remove cells that come from pertubrbation but have label ctrl_like
mask1 <- progenitors$perturbation == "notch" & progenitors$VFC_2 == "ctrl_like"

# remove cells that come from ctrl but have label notch_like
mask2 <- progenitors$perturbation == "ctrl" & progenitors$VFC_2 == "notch_like"

progenitors <- progenitors[, !(mask1 | mask2)]
progenitors@meta.data$perturbation <- ifelse(progenitors$perturbation == "ctrl", "Control", "perturbed Notch KO")


gene = "CG9650"
p <- FetchData(progenitors[,progenitors$high_res_annotation == "EEP"], c(gene, "perturbation")) %>%
    rownames_to_column("id") %>%
    pivot_longer(-c(id, perturbation)) %>%
    ggplot(., aes(x = perturbation, y = value, color = perturbation, fill = perturbation)) +
    geom_jitter(size = 0.65, stroke = 0.4, width = 0.2, shape = 21) +
    geom_violin(
        mapping = aes(x = perturbation, y = value), color = "black",
        adjust = 1, trim = TRUE, scale = "width", inherit.aes = F, fill=NA, width=0.4 # adjust width so the violine does not stick out too much
    ) +
    theme_Publication() +
    theme(legend.position = "none") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    stat_summary(
        fun = mean, geom = "point", shape = 8, color = "black", stroke = 0.85, show.legend = F,
        aes(group = perturbation), position = position_dodge(width = 0.9)
    ) +
    ylab("Expression\n(logcounts)") +
    xlab("Condition") +
    scale_color_manual(values = c(color_mapping[1], color_mapping[4])) +
    scale_fill_manual(values = alpha(c(color_mapping[1], color_mapping[4]), 0.3)) +
    ggtitle(gene)+
    ggsignif::geom_signif(
        comparisons = list(c("Control", "perturbed Notch KO")),
        map_signif_level = TRUE, textsize = 6, color="black")


ggsave(
    filename = here("plots", "main", "Fig2_Cph_EEP_expression.pdf"),
    plot = p,
    height = 4, width = 5, scale = 1.3
)

```


