---
title: "Figure 2 Delta gating Cph Expression"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```



### Load data and determine which cells express "high" delta
```{r}
seurat <- readRDS(here("output", "Ctrl_NotchKO_integrated_scent.rds"))
seurat_isc <- seurat[, seurat$celltype_manual == "ISC"]

# we will define high delta expression as top 75percentile and low delta expression as lower 25 percentile
delta_classification <- lapply(setNames(unique(seurat$perturbation), unique(seurat$perturbation)), function(perturbation) {
    tmp <- seurat[, seurat$perturbation == perturbation & seurat$celltype_manual == "ISC"]
    stats <- summary(tmp@assays$RNA@data["Dl", ])
    print(stats)

    tmp@assays$RNA@data["Dl", ] %>%
        enframe(name = "barcode", value = "expression") %>%
        mutate(Delta_status = case_when(
            expression >= stats["3rd Qu."] ~ "high",
            expression <= stats["1st Qu."] ~ "low",
            T ~ "medium"
        ))
}) %>% bind_rows()

stopifnot(all(delta_classification$barcode == Cells(seurat_isc)))
seurat_isc$Delta_status <- delta_classification$Delta_status
```


### Draw some violine plots
```{r}
p <- FetchData(seurat_isc, c("CG9650", "perturbation", "Delta_status")) %>%
    filter(Delta_status != "medium") %>%
    mutate(dummy = ifelse(.$Delta_status == "high", "X", "Z")) %>% # necessary to color the violines black...
    rownames_to_column("id") %>%
    mutate(Delta_status = factor(Delta_status, levels = c("low", "high"))) %>%
    pivot_longer(-c(id, perturbation, Delta_status, dummy)) %>%
    ggplot(., aes(x = perturbation, y = value, color = Delta_status, fill = Delta_status)) +
    geom_point(size = 0.65, stroke = 0.4, shape = 21, position = position_jitterdodge(jitter.width = 0.3)) +
    geom_violin(
        mapping = aes(x = perturbation, y = value, color = dummy), inherit.aes = F,
        adjust = 1, trim = TRUE, fill = NA,
        scale = "width", show.legend = F,
        width = 0.72 # adjust width so the violine does not stick out too much
    ) +
    theme_Publication_side_legend() +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    stat_summary(
        fun = mean, geom = "point", shape = 8, color = "black", stroke = 0.85, show.legend = F,
        aes(group = Delta_status), position = position_dodge2(width = 0.72)
    ) +
    ylab("Expression\n(logcounts)") +
    xlab("Condition") +
    scale_color_manual(values = c(c("#f0bb47", "#996c09"), "black", "black"), breaks = c("low", "high")) +
    scale_fill_manual(values = alpha(c("#f0bb47", "#996c09"), 0.3))

p
ggsave(
    filename = here("plots", "main", "Fig2_Delta_gating_ISC_Cph_expr.pdf"),
    plot = p,
    height = 3, width = 4.5, scale = 1.3
)
```


# now check if the expression is different between high and low of the same condition
```{r}
res <- parallel::mclapply(unique(seurat_isc$perturbation), function(condition) {
    tmp <- seurat_isc[, seurat_isc$perturbation == condition]
    Idents(tmp) <- tmp$Delta_status
    FindMarkers(tmp,
        ident.1 = "high", ident.2 = "low",
        logfc.threshold = 0, min.pct = 0
    ) %>%
        rownames_to_column("gene") %>%
        mutate(condition = condition)
}, mc.cores = 5)
```



```{r}
sessionInfo()
```

