---
title: "Figure 2 Generate pseudotime heatmap for ISC EE lineage"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)
library(ComplexHeatmap)
library(circlize)
library(tradeSeq)
library(SingleCellExperiment)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```



```{r}
seurat <- readRDS(here("output", "seuratKO_slingshot_object_integrated.rds"))
gam_fit_6 <- readRDS(here("output", "tradeSeq_fit_condiments_strict.rds"))
condRes_split <- readRDS(here("output", "tradeSeq_condition_test_res_strict.rds"))


# get genes that are differentiall expressed along lineage 4 (ISC-->EEP-->EE)
genes_of_interest <- condRes_split$Lineage4 %>%
    filter(padj_lineage4 < 0.05) %>%
    pull(gene)

# get expression along lineage4.
# see this issue on why we have to use tidy=T https://github.com/statOmics/tradeSeq/issues/232
yhatSmooth <- predictSmooth(gam_fit_6, gene = genes_of_interest, nPoints = 1500, tidy = TRUE)
yhatSmooth_subset <- yhatSmooth %>%
    filter(lineage == 4) %>% # corresponds to ISC-->EEP-->EE
    select(-lineage) %>%
    unite(col = "combined", c(time, condition)) %>%
    pivot_wider(names_from = combined, values_from = yhat) %>%
    column_to_rownames("gene")

# make sure that the columns are correctly ordered. first there should be 1500 ctrls then 1500 notch samples
rle(grepl("_ctrl", colnames(yhatSmooth_subset)))
rle(grepl("_notch", colnames(yhatSmooth_subset)))

# now make sure the time also matches
original_time_ctrl <- yhatSmooth %>%
    filter(lineage == 4) %>%
    filter(condition == "ctrl") %>%
    pull(time) %>%
    unique()
isSorted(original_time_ctrl)
all((colnames(yhatSmooth_subset)[1:1500] %>% str_remove_all(., "_ctrl")) == original_time_ctrl)

original_time_notch <- yhatSmooth %>%
    filter(lineage == 4) %>%
    filter(condition == "notch") %>%
    pull(time) %>%
    unique()
isSorted(original_time_notch)
all((colnames(yhatSmooth_subset)[1501:3000] %>% str_remove_all(., "_notch")) == original_time_notch)


# now the we have made sure the column order is correct, we can replace them with random stuff
generate_random_string <- function(length = 15) {
    # Define the set of characters to sample from (uppercase and lowercase letters)
    chars <- c(letters, LETTERS)
    # Sample 'length' number of characters and collapse them into a single string
    random_string <- paste(sample(chars, length, replace = TRUE), collapse = "")
    return(random_string)
}

colnames(yhatSmooth_subset) <- sapply(1:3000, function(x) generate_random_string())

####################
# GENERATE HEATMAP #
####################
column_names <- c(
    rep("Control", 1500),
    rep("Notch knockout", 1500)
)



ha <- HeatmapAnnotation(
    perturbation =
        anno_block(
            gp = gpar(fill = c(
                color_mapping[1],
                color_mapping[3]
            )),
            labels = c("Control", "Notch knockout"),
            labels_gp = gpar(
                col = "black",
                fontsize = 7,
                fontface = "bold"
            )
        )
)
m <- as.matrix(yhatSmooth_subset) %>%
    t() %>%
    scale() %>%
    t()
rownames(m) <- rownames(yhatSmooth_subset)


cap_value <- 4
m[m > cap_value] <- cap_value
m[m < -cap_value] <- -cap_value
col_fun <- colorRamp2(c(-cap_value, 0, cap_value), c("blue", "white", "red"))


# update name of Cph
rownames(m) <- ifelse(rownames(m) == "CG9650", "Cph", "")

heatmap <- Heatmap(m,
    cluster_rows = T,
    cluster_columns = F,
    show_row_names = T,
    show_column_names = F,
    show_row_dend = F,
    name = "Z-score",
    border = "black",
    top_annotation = ha,
    row_names_gp = grid::gpar(fontsize = 7),
    row_gap = unit(1, "mm"),
    column_gap = unit(1, "mm"),
    column_split = column_names,
    use_raster = F,
    column_title = "Lineage: ISC -> EEP -> EE",
    column_title_gp = gpar(fontsize = 7, fontface = "bold"),
    column_title_rot = 0,
    show_heatmap_legend = T, row_names_side = "left"
)

pdf(here::here("plots", "main", "Fig2_pseudotime_heatmap_ISC_EE.pdf"),
    height = 5, width = 4
)
heatmap
dev.off()
```

```{r}
sessionInfo()
```

