---
title: "Figure 4 Highlight coexpression of sc and Cph"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)

# source plotting theme
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```

```{r}
special_dimplot <- function(seurat, feature, dim_reduction = "umap", ...) {
    embedding_df <- Embeddings(seurat, dim_reduction)
    data <- FetchData(seurat, feature)
    if (n_distinct(data[[feature]]) > 20) {
        print("Assuming the feature of interest is numeric")
        data[[feature]] <- as.numeric(data[[feature]])
    }

    stopifnot(all(rownames(embedding_df) == rownames(data)))
    data <- cbind(data, embedding_df)
    # calculate the median position of each cluster centroid
    centroids_data <- data %>%
        group_by(tmp_celltype) %>%
        summarise(
            m_umap1 = median(UMAP_1),
            m_umap2 = median(UMAP_2)
        )
    embedding_colnames <- colnames(data)[(ncol(data) - 1):ncol(data)]
    p <- ggplot(data, aes(!!sym(embedding_colnames[[1]]),
        !!sym(embedding_colnames[[2]]),
        color = !!sym(feature)
    )) +
        geom_point(...) +
        ggrepel::geom_label_repel(data = centroids_data, mapping = aes(x = m_umap1, y = m_umap2, fill = tmp_celltype, label = tmp_celltype), color = "black")
    if (n_distinct(data[[feature]]) < 20) {
        p <- p +
            guides(color = guide_legend(override.aes = list(size = 1.3)))
    }
    return(p)
}
```


```{r}
seurat <- readRDS(here::here("output", "Ctrl_Notch_NotchCphRNAi_integrated_scent.rds"))

seurat@meta.data$tmp_celltype <- case_when(
    seurat$high_res_annotation == "EEP" ~ "EEP",
    T ~ seurat$celltype_manual
)
seurat$tmp_celltype <- factor(seurat$tmp_celltype,
    levels =
        c("ISC", "EEP", "EB", "dEC", "daEC", "aEC", "mEC", "Copper", "LFC", "pEC", "EE", "MT")
)




p <- special_dimplot(seurat,
    feature = "tmp_celltype", size = 0.05,
    shape = 19,
    stroke = 0.25
) +
    scale_color_manual(values = sapply(c("ISC", "EEP", "EB", "dEC", "daEC", "aEC", "mEC", "Copper", "LFC", "pEC", "EE", "MT"), get)) +
    scale_fill_manual(values = sapply(c("ISC", "EEP", "EB", "dEC", "daEC", "aEC", "mEC", "Copper", "LFC", "pEC", "EE", "MT"), get)) +
    small_axis("UMAP ", fontsize = 4, arrow_length = 17) +
    ggtitle("Control") +
    theme(
        legend.position = "none"
    ) +
    scale_y_reverse()

ggsave(
    plot = p,
    filename = here::here("scRNAseq","plots", "main", "Fig5A_RNAi_experiments_celltype.pdf"),
    width = 5,
    height = 5
)



seurat$perturbation <- factor(seurat$perturbation, levels = c("ctrl", "NotchRNAi", "NotchCphRNAi"))
p <- new_dimplot(seurat,
    feature = "perturbation", size = 0.05,
    shape = 19,
    stroke = 0.25
) +
    small_axis("UMAP ", fontsize = 4, arrow_length = 17) +
    scale_color_manual(values = c(color_mapping[1], color_mapping[4], "#00ba38")) +
    ggtitle("Control") +
    theme(
        plot.title = element_blank()
    ) +
    scale_y_reverse()


ggsave(
    plot = p,
    filename = here::here("scRNAseq","plots", "main", "Fig5A_RNAi_experiments_condition.pdf"),
    width = 5.5,
    height = 5
)
```

```{r}
sessionInfo()
```

```

