---
title: "Supplementary figure 9"
author: "Erica Valentini"
date: "2024-09-05"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
    smooth_scroll: yes
  pdf_document: default
  number_sections: no
  highlight: tango
  theme: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE, cache = FALSE)
```

**Last modified:**
```{r}
print(date())
```

# Load packages and data

```{r load}
library(tidyverse)
library(ggrepel)
library(Seurat)
library(ggpubr)

source("../../../../plot_theme.R")

integrated <- readRDS("../../../main_figures/Figure5/raw_data/integrated.rds")

NotchCph_ISC_EB <- read_tsv("../raw_data/MAST_diff_expr_NotchCphRNAi_Progenitor_coarse.tsv")
Notch_ISC_EB <- read_tsv("../raw_data/MAST_diff_expr_NotchRNAi_Progenitor_coarse.tsv")
NotchCph_ISC <- read_tsv("../raw_data/MAST_diff_expr_NotchCphRNAi_ISC_granular.tsv")
Notch_ISC <- read_tsv("../raw_data/MAST_diff_expr_NotchRNAi_ISC_granular.tsv")

interesting_genes <- c("E(spl)malpha-BFM", "klu", "Dl", "Swim", "E(spl)mbeta-HLH", "Myc", "spdo", "sli", "crol", "endos", "arm", "msi", "Non1", "mnb", "sima", "Mad", "path", "Egfr", "mira", "EcR", "N", "mip40", "CycA", "InR", "Dp", "esg", "kuz", "kibra", "Cdc7", "grp", "Pdi", "Cph", "sc")

```


# Supplementary Figure 9 A and B


```{r violin_plot_multiple_genes}

genes_to_plot_violin <- c("N", "CG9650")
celltypes_to_plot <- "ISC"
violin_plot_input <- FetchData(integrated, c(genes_to_plot_violin, "high_res_annotation", "perturbation"))
violin_plot_input <- violin_plot_input %>% 
  filter(perturbation %in% c("ctrl", "NotchRNAi", "NotchCphRNAi")) %>% 
  rename("Cph" = "CG9650") %>% 
  rename("Notch" = "N") %>% 
  mutate(perturbation = factor(perturbation, levels = c("ctrl", "NotchRNAi", "NotchCphRNAi")))

my_comparisons <- list( c("ctrl", "NotchRNAi"), c("ctrl", "NotchCphRNAi"))


vln_plot <- function(gene, celltype, celltype_title, adjust_ = 1) {
    violin_plot_input %>%
    filter(high_res_annotation %in% celltype) %>% 
    select(gene, perturbation) %>% 
    rename(value = gene) %>% 
    ggplot(aes(x = perturbation, y = value, color = perturbation, fill = perturbation)) +
    geom_jitter(size = 0.65, stroke = 0.4, width = 0.2, shape = 21) +
    geom_violin(
        adjust = adjust_, trim = TRUE, scale = "width", fill="#00000000",color="black", width=0.6
    ) +
    theme_Publication() +
    theme(legend.position = "none") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    stat_summary(
        fun = mean, geom = "point", shape = 8, color = "black", stroke = 0.85, show.legend = F,
        aes(group = perturbation), position = position_dodge(width = 0.9)
    ) +
    stat_compare_means(comparisons = my_comparisons, method = "t.test", label = "p.signif") +
    ylab("Expression\n(logcounts)") +
    xlab("Condition") +
    ggtitle(paste0(gene, " expression in: ", celltype_title))
}

vln_plot(gene = "Notch", celltype = "ISC", celltype_title = "ISC")
ggsave(filename = "../Graphics/9A_vln_plot.pdf", device = "pdf")

vln_plot(gene = "Cph", celltype = "ISC", celltype_title = "ISC")
ggsave(filename = "../Graphics/9B_vln_plot.pdf", device = "pdf")

```


# Supplementary Figure 9 D and E

## Prepare data

```{r prepare_data}

differentially_expressed_genes <- Notch_ISC %>% bind_rows(NotchCph_ISC) %>% bind_rows(Notch_ISC_EB) %>% bind_rows(NotchCph_ISC_EB) %>% mutate(celltype = ifelse(celltype == "Progenitor", "ISC-EB", celltype))
```

## Correlation plot

```{r FC correlation}

pvalue_threshold = 0.05

correlation_plot <- function(data, cell_type){
  data %>% 
  filter(celltype == cell_type, condition == "NotchCphRNAi", p_adj < pvalue_threshold) %>% 
  inner_join(data %>% filter(condition == "NotchRNAi", p_adj < pvalue_threshold, celltype == cell_type), by = "gene", suffix = c(".notch.cph", ".notch")) %>% 
  mutate(is_interesting = ifelse(gene %in% interesting_genes, "interesting", "not interesting")) %>% 
  arrange(desc(is_interesting)) %>% 
  ggscatter(x="logFC.notch", 
            y = "logFC.notch.cph", 
            color = "is_interesting",
            legend = "none",
            add = "reg.line", 
            conf.int = TRUE, 
            palette = c("red", "gray10"), 
            add.params = list(color = "blue", fill="lightgray"), 
            alpha = 0.7) +
    geom_rug(side = "bi", aes(color = is_interesting), palette = c("red", "gray10")) +
    stat_cor(method = "pearson") +
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_vline(xintercept = 0, linetype = "dashed") +
    geom_text_repel(aes(label = if_else(gene %in% interesting_genes, gene, "")), max.overlaps = Inf, box.padding = 0.5) +
    ggtitle(cell_type)
}
  
correlation_plot(differentially_expressed_genes, "ISC")
ggsave(filename = "../Graphics/9D_correlation_plot.pdf", device = "pdf")

correlation_plot(differentially_expressed_genes, "ISC-EB")
ggsave(filename = "../Graphics/9E_correlation_plot.pdf", device = "pdf")

```


# R session info

```{r}
sessionInfo()
```