---
title: "Celltype assignment for Cph up done manually"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

## Introduction
Do celltype annotation.

```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(circlize)
library(ComplexHeatmap)
library(here)
library(SingleCellExperiment)
source(here("plot_theme.R"))
source(here("helper_functions.R"))
set.seed(123)
```

## Automatic cell type labeling

```{r}
# load integrated CphUp dataset.
CphUp <- readRDS(here("output", "CphUp_seurat_integrated.rds"))


# currated table of marker genes based on the literature such as https://www.pnas.org/doi/10.1073/pnas.1916820117 or https://www.science.org/doi/10.1126/science.abk2432 or
# https://www.sciencedirect.com/science/article/pii/S2211124715006075
marker_table <- data.frame(gene=c("betaTry", "epsilonTry", "alphaTry", 
                             "nub", "Myo31DF",
                             "esg", "N", "E(spl)mbeta-HLH", "klu",
                             "Dl",
                             "Vha100-4", "Vha16-1", "MtnC", "CG17109",
                             "pros", "7B2", "IA-2", 
                             "PGRP-SC1a", "PGRP-SC1b","Jon65Ai", "Jon65Aii", "Jon66Ci", "Jon66Cii",
                             "lambdaTry", "LManVI", "iotaTry", "etaTry", "zetaTry", 
                             "thetaTry", "Npc2f",
                             "Smvt","ct"),
                      celltype=c("aEC", "aEC", "aEC", 
                                 "dEC", "dEC", 
                                 "EB", "EB", "EB", "EB", 
                                 "ISC",
                                 "Copper\ncells", "Copper\ncells", "Copper\ncells", "Copper\ncells", 
                                 "EE", "EE", "EE", 
                                 "LFC", "LFC", "LFC", "LFC", "LFC", "LFC", "LFC",
                                 "pEC","pEC","pEC","pEC",
                                 "mEC", "mEC",
                                 "MT","MT"))

DefaultAssay(CphUp) <- "integrated"
CphUp<-DietSeurat(CphUp)
CphUp <- run_seurat_steps(CphUp, include_norm = F, include_leiden = F, include_louvain = T)
DefaultAssay(CphUp) <- "RNA"

Idents(CphUp) <- factor(CphUp$integrated_snn_res.1.5, levels = as.character(0:27))
p<-marker_heatmap(seurat = CphUp,
               markers = marker_table$gene,
               celltype = marker_table$celltype,
               group.by = "integrated_snn_res.1.5",
               cap_value = 3)
p

# based on the heatmap  assign the labels
# really hard to specifically pick out an ISC cluster.
CphUp$celltype_manual <- case_when(
  CphUp$integrated_snn_res.1.5 == 0 ~ "ISC",
  CphUp$integrated_snn_res.1.5 == 1 ~ "EB",
  CphUp$integrated_snn_res.1.5 == 2 ~ "EB",
  CphUp$integrated_snn_res.1.5 == 3 ~ "EB",
  CphUp$integrated_snn_res.1.5 == 4 ~ "pEC",
  CphUp$integrated_snn_res.1.5 == 5 ~ "aEC",
  CphUp$integrated_snn_res.1.5 == 6 ~ "aEC",
  CphUp$integrated_snn_res.1.5 == 7 ~ "EB",
  CphUp$integrated_snn_res.1.5 == 8 ~ "aEC",
  CphUp$integrated_snn_res.1.5 == 9 ~ "aEC",
  CphUp$integrated_snn_res.1.5 == 10 ~ "EB",
  CphUp$integrated_snn_res.1.5 == 11 ~ "EB",
  CphUp$integrated_snn_res.1.5 == 12 ~ "pEC",
  CphUp$integrated_snn_res.1.5 == 13 ~ "dEC",
  CphUp$integrated_snn_res.1.5 == 14 ~ "MT",
  CphUp$integrated_snn_res.1.5 == 15 ~ "LFC",
  CphUp$integrated_snn_res.1.5 == 16 ~ "aEC",
  CphUp$integrated_snn_res.1.5 == 17 ~ "aEC",
  CphUp$integrated_snn_res.1.5 == 18 ~ "EB",
  CphUp$integrated_snn_res.1.5 == 19 ~ "aEC",
  CphUp$integrated_snn_res.1.5 == 20 ~ "Copper",
  CphUp$integrated_snn_res.1.5 == 21 ~ "pEC",
  CphUp$integrated_snn_res.1.5 == 22 ~ "EE",
  CphUp$integrated_snn_res.1.5 == 23 ~ "mEC",
  CphUp$integrated_snn_res.1.5 == 24 ~ "unk",
  CphUp$integrated_snn_res.1.5 == 25 ~ "unk",
  CphUp$integrated_snn_res.1.5 == 26 ~ "unk",
  CphUp$integrated_snn_res.1.5 == 27 ~ "aEC",
  T ~ CphUp$integrated_snn_res.1.5
)


CphUp$celltype_manual <- factor(CphUp$celltype_manual, 
                               levels = c("ISC", "EB","dEC","aEC", "Copper", "mEC" , "LFC", "pEC", "EE", "MT","unk"))
saveRDS(CphUp, here("output", "CphUp_seurat_integrated_annotated.rds"))
```

```{r, echo=T, message=T, error=T}
sessionInfo()
```
