---
title: "Profile the cell type abundance changes"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r load libraries}
library(here)
library(Seurat)
library(tidyverse)
library(patchwork)
library(DESeq2)
library(ggsignif)


# load custom functions
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


## Check for significant changes in celltype abundance

```{r}
integrated <- readRDS(here("output", "Ctrl_NotchKO_integrated_scent.rds"))
integrated@meta.data$celltype_manual <- ifelse(integrated@meta.data$celltype_manual == "unk2", "unk", integrated@meta.data$celltype_manual)

# rename celltypes and remove celltypes we are not interested in.
integrated@meta.data$tmp_celltype <- case_when(
    # we are only interested in differentiated celltypes and progenitor cell types. No intermediate celltypes
    integrated$celltype_manual %in% c("daEC", "dEC", "MT", "unk", "unk2") ~ NA_character_,
    # we combine the different regional EC into one population
    grepl("EC", integrated$celltype_manual) ~ "EC",
    integrated$celltype_manual == "LFC" ~ "EC",
    integrated$celltype_manual == "Copper" ~ "EC",
    integrated$high_res_annotation == "EEP" ~ "EEP",
    T ~ integrated$celltype_manual
)

integrated@meta.data$orig.ident <- case_when(
    integrated$orig.ident == "TX22" ~ "Control Replicate 1",
    integrated$orig.ident == "TX23" ~ "Control Replicate 2",
    integrated$orig.ident == "TX22_N" ~ "Notch Replicate 1",
    integrated$orig.ident == "TX23_N" ~ "Notch Replicate 2",
) %>% factor(., levels = c(
    "Control Replicate 1", "Control Replicate 2",
    "Notch Replicate 1", "Notch Replicate 2"
))
integrated_subset <- integrated[, !is.na(integrated$tmp_celltype)]

# create "count table" for DESeq2
cnts <- integrated_subset@meta.data %>%
    group_by(orig.ident, tmp_celltype) %>%
    tally() %>%
    pivot_wider(.,
        names_from = "orig.ident",
        values_from = "n"
    ) %>%
    column_to_rownames("tmp_celltype") %>%
    as.matrix()

# define model matrix
exp_design <- integrated_subset@meta.data[, c("orig.ident", "perturbation")] %>%
    data.frame() %>%
    distinct()

exp_design$orig.ident <- factor(exp_design$orig.ident, levels = c(
    "Control Replicate 1", "Control Replicate 2",
    "Notch Replicate 1", "Notch Replicate 2"
))
rownames(exp_design) <- exp_design$orig.ident
dds <- DESeqDataSetFromMatrix(
    countData = cnts,
    colData = exp_design,
    design = ~perturbation
)

# we dont use deseq2 to calculate norm factors because it assumes that majority of genes (in this case celltypes) dont change.
# This assumption doesnt hold in our case.
sizeFactors(dds) <- colSums(cnts) / mean(colSums(cnts))
# run DESeq2.
result <- DESeq(dds, fitType = "local") # this does not really fit a trend because we dont have enough samples anyway. if we keep the default "parametric", deseq2 will automatically fit a local one.

out_deseq <- results(result) %>%
    data.frame() %>%
    arrange(padj)
out_deseq

#####################
# VISUALIZE RESULTS #
#####################
plot_df <- counts(dds, norm = T) %>%
    data.frame() %>%
    rownames_to_column("celltype") %>%
    pivot_longer(-celltype, names_to = "replicate", values_to = "n_cells") %>%
    mutate(celltype = factor(celltype, levels = c("ISC", "EEP", "EE", "EB", "EC"))) %>%
    mutate(replicate = str_replace_all(.$replicate, "\\.", " ")) %>%
    mutate(replicate = factor(replicate, levels = c("Control Replicate 1", "Control Replicate 2", "Notch Replicate 1", "Notch Replicate 2"))) %>%
    mutate(Condition = ifelse(grepl("Notch", replicate), "Notch\nknockout", "Control"))

# we also have to create a dummy df to make space for the significance asterics...
dummy <- data.frame(
    celltype = c("ISC", "EEP", "EE", "EB", "EC"), n_cells = c(4700, 900, 860, 4600, 4400), Condition = "Control",
    variable = "celltype", stringsAsFactors = FALSE, replicate = "Control Replicate 1"
)
dummy$celltype <- factor(dummy$celltype, levels = c("ISC", "EEP", "EE", "EB", "EC"))

# create a dataframe for the significance stars
annotation_df <- data.frame(
    celltype = c("ISC", "EEP", "EE", "EB", "EC"),
    start = c("Control"),
    end = c("Notch\nknockout"),
    y = c(4200, 800, 800, 4200, 4000),
    label = c("\n***", "\n**", "\n**", "\n***", "n.s.")
)
annotation_df$celltype <- factor(annotation_df$celltype, levels = c("ISC", "EEP", "EE", "EB", "EC"))

p <- ggplot(plot_df, aes(x = Condition, y = n_cells, color = replicate)) +
    geom_point(size = 1.5) +
    geom_blank(dummy, mapping = aes(x = Condition, y = n_cells, color = replicate)) +
    geom_signif(
        data = annotation_df,
        mapping = aes(xmin = start, xmax = end, annotations = label, y_position = y, tip_length = 0),
        textsize = 4.3, vjust = 0.0,
        manual = TRUE,
        inherit.aes = FALSE
    ) +
    stat_summary(
        fun = "mean", geom = "crossbar",
        mapping = aes(ymin = ..y.., ymax = ..y..), width = 0.2, show.legend = FALSE, color = "red"
    ) +
    facet_wrap(~celltype, scales = "free_y", ncol = 5) +
    ylab("Normalized\nnumber of cells") +
    theme_Publication() +
    theme(
        legend.position = "none", # maybe we will change this later
        axis.title = element_text(size = 9, face = "bold"),
        axis.text = element_text(size = 8),
        strip.text.x = element_text(size = 8, face = "bold")
    ) +
    scale_color_manual(values = color_mapping) +
    guides(color = guide_legend(nrow = 5, byrow = F))
p
```





### EE specific abundance change
```{r}
## Abundance change including classIII
ee <- integrated[, integrated$celltype_manual == "EE"]

cnts <- ee@meta.data %>% 
  group_by(orig.ident, high_res_annotation) %>% 
  tally() %>% 
  pivot_wider(., names_from = "orig.ident",
              values_from = "n") %>% 
  column_to_rownames("high_res_annotation") %>% 
  as.matrix() 

exp_design <- data.frame(orig.ident=c("Control Replicate 1","Control Replicate 2", "Notch Replicate 1", "Notch Replicate 2"),
                         perturbation = c("ctrl", "ctrl", "notch", "notch"))
rownames(exp_design) <- exp_design$orig.ident

# rearrange columns
cnts <- cnts[,rownames(exp_design)]
dds <- DESeqDataSetFromMatrix(countData = cnts,
                              colData = exp_design,
                              design = ~perturbation)
sizeFactors(dds) = colSums(cnts)/mean(colSums(cnts))
result <- DESeq(dds, fitType = "local") # this does not really fit a trend because we dont have enough samples anyway. if we keep the default "parametric", deseq2 will automatically fit a local one.
out_deseq <- results(result) %>% 
  data.frame() %>% 
  arrange(padj)
out_deseq

#########################################
# VISUALIZE RESULTS FOR AstC and Tk EEs #
#########################################
plot_df  <- counts(dds, norm=T) %>% 
  data.frame() %>% 
  rownames_to_column("celltype") %>% 
  filter(celltype %in% c("Tk-EE", "AstC-EE", "classIII-EE")) %>% 
  pivot_longer(-celltype,names_to = "replicate", values_to = "n_cells") %>% 
  mutate(celltype=factor(celltype, levels=c("AstC-EE","Tk-EE", "classIII-EE"))) %>% 
  mutate(Condition = ifelse(grepl("N",replicate), "Notch\nknockout","Control")) %>% 
  mutate(replicate = factor(replicate, levels = c("TX22","TX23", "TX22_N", "TX23_N")))

# we also have to create a dummy df to make space for the significance asterics...
dummy <- data.frame(celltype = c("AstC-EE", "Tk-EE", "classIII-EE"), n_cells=c(420, 410,145), Condition = "Control",
                    variable = "celltype", stringsAsFactors=FALSE, replicate="TX22")
dummy$celltype <- factor(dummy$celltype , levels=c("AstC-EE", "Tk-EE", "classIII-EE"))

# create a dataframe for the significance stars
annotation_df <- data.frame(
  celltype = c("AstC-EE", "Tk-EE", "classIII-EE"),
  start = c("Control"), 
  end = c("Notch\nknockout"),
  y = c(410, 390, 140),
  label = c("*", "*", "n.s.")
)
annotation_df$celltype <- factor(annotation_df$celltype , levels=c("AstC-EE", "Tk-EE", "classIII-EE"))

p <- ggplot(plot_df, aes(x=Condition, y=n_cells,color=replicate))+
  geom_point(size=0.8)+
  geom_blank(dummy, mapping=aes(x=Condition, y=n_cells,color=replicate)) +
  geom_signif(
    data = annotation_df,
    mapping=aes(xmin = start, xmax = end, annotations = label, y_position = y, tip_length=0),
    textsize = 3, vjust = 0.4,
    manual = TRUE,
    inherit.aes = FALSE
  )+
  stat_summary(fun="mean", geom="crossbar",
               mapping=aes(ymin=..y.., ymax=..y..), 
               width=0.2, show.legend = FALSE, color="red",
               fatten=1)+
  facet_wrap(~celltype, scales = "free_y", ncol = 4) + 
  ylab("Normalized\nnumber of cells") +
  theme_Publication_side_legend() +
  theme(legend.position = "none", # maybe we will change this later
        axis.title = element_text(size=6, face = "bold"),
        axis.text =  element_text(size=6),
        axis.ticks = element_line(linewidth = 0.3),
        strip.text.x = element_text(size = 5.5, face="bold"),
        axis.line = element_line(linewidth = 0.35))+ 
  scale_color_manual(values=color_mapping)+
  guides(color=guide_legend(nrow=4, byrow=F))
p
```


```{r}
sessionInfo()
```



