---
title: "Profile the cell type abundance changes for the RNAi dataset"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r load libraries}
library(here)
library(Seurat)
library(tidyverse)
library(patchwork)
library(DESeq2)


# load custom functions
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


## Show abundance changes as a stacked barchart
We cant do any real statistics, because we only have one replicate for NotchRNAi and NotchCphRNAi

```{r}
seurat_integrated <- readRDS(here("output", "Ctrl_Notch_NotchCphRNAi_integrated_scent.rds"))

### Visualize some stats for the different replicates
cell_fractions <- seurat_integrated@meta.data %>%
    filter(perturbation %in% c("NotchRNAi", "ctrl", "NotchCphRNAi")) %>%
    group_by(orig.ident.unique, celltype_manual) %>%
    tally() %>%
    left_join(., table(seurat_integrated$orig.ident.unique) %>%
        enframe(name = "orig.ident.unique", value = "n_total")) %>%
    mutate(fraction = n / n_total) %>%
    mutate(condition = str_remove_all(orig.ident.unique, "TX\\d+_")) %>%
    mutate(celltype_manual = factor(celltype_manual, levels = c("ISC", "EB", "dEC", "daEC", "aEC", "Copper", "mEC", "pEC", "LFC", "EE", "MT")))

cell_fractions <- cell_fractions %>%
    group_by(condition, celltype_manual) %>%
    summarise(mean_fraction = mean(fraction)) %>%
    mutate(condition = ifelse(condition == "rep1_NotchCphRNAi", "NotchCphRNAi", condition)) %>%
    mutate(condition = factor(condition, levels = c("ctrl", "NotchRNAi", "NotchCphRNAi")))

ggplot(cell_fractions, aes(x = condition, y = mean_fraction, fill = celltype_manual)) +
    geom_bar(stat = "identity") +
    theme_Publication_side_legend() %+%
    theme(
        panel.grid.major = element_blank(),
        legend.title = element_blank()
    ) +
    scale_color_manual(values = c(ISC, EB, dEC, daEC, aEC, Copper, mEC, pEC, LFC, EE, MT)) +
    scale_fill_manual(values = c(ISC, EB, dEC, daEC, aEC, Copper, mEC, pEC, LFC, EE, MT)) +
    ylab("Fraction") +
    xlab("Condition") +
    scale_y_continuous(expand = c(0, 0))

### summarize some celltypes
tmp_seurat_integrated <- seurat_integrated[, !seurat_integrated$celltype_manual %in% c("daEC", "dEC", "MT", "unk", "unk2")]
cell_fractions <- tmp_seurat_integrated@meta.data %>%
    filter(perturbation %in% c("NotchRNAi", "ctrl", "NotchCphRNAi")) %>%
    mutate(tmp_celltype = case_when(
        grepl("EC", celltype_manual) ~ "EC",
        celltype_manual == "LFC" ~ "EC",
        celltype_manual == "Copper" ~ "EC",
        T ~ celltype_manual
    )) %>%
    filter(!is.na(tmp_celltype)) %>%
    group_by(orig.ident.unique, tmp_celltype) %>%
    tally() %>%
    left_join(., table(tmp_seurat_integrated$orig.ident.unique) %>%
        enframe(name = "orig.ident.unique", value = "n_total")) %>%
    mutate(fraction = n / n_total) %>%
    mutate(condition = str_remove_all(orig.ident.unique, "TX\\d+_")) %>%
    mutate(tmp_celltype = factor(tmp_celltype, levels = c("ISC", "EE", "EB", "EC")))

cell_fractions <- cell_fractions %>%
    group_by(condition, tmp_celltype) %>%
    summarise(mean_fraction = mean(fraction)) %>%
    mutate(condition = ifelse(condition == "rep1_NotchCphRNAi", "NotchCphRNAi", condition)) %>%
    mutate(condition = factor(condition, levels = c("ctrl", "NotchRNAi", "NotchCphRNAi")))


p <- ggplot(cell_fractions, aes(x = condition, y = mean_fraction, fill = tmp_celltype)) +
    geom_bar(stat = "identity") +
    theme_Publication_side_legend() %+%
    theme(
        panel.grid.major = element_blank(),
        legend.title = element_blank()
    ) +
    scale_color_manual(values = c(ISC, EE, EB, LFC)) +
    scale_fill_manual(values = c(ISC, EE, EB, LFC)) +
    ylab("Fraction") +
    xlab("Condition") +
    scale_y_continuous(expand = c(0, 0))
p
```



```{r}
sessionInfo()
```

