---
title: "EV4C Show Cph Expression in all celltypes as Violine plot"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```



```{r}
# load progenitor population with MELD labels
integrated <- readRDS(here("output", "Ctrl_NotchKO_integrated_scent.rds"))
integrated@meta.data$tmp_celltype <- case_when(
    integrated$high_res_annotation == "EEP" ~ "EEP",
    T ~ integrated$celltype_manual
)
integrated <- integrated[, !integrated$celltype_manual %in% c("unk", "unk2", "MT")]
integrated@meta.data$tmp_celltype <- factor(
    integrated@meta.data$tmp_celltype,
    levels = c("ISC", "EEP", "EB", "dEC", "daEC", "aEC", "mEC", "Copper", "LFC", "pEC", "EE")
)



gene="CG9650"
p <- FetchData(integrated, c(gene, "perturbation", "tmp_celltype")) %>%
    rownames_to_column("id") %>%
    pivot_longer(-c(id, perturbation, tmp_celltype)) %>%
    ggplot(., aes(x = tmp_celltype, y = value, color = perturbation, fill = perturbation)) +
    geom_violin(
        aes(x = tmp_celltype, y = value),
        adjust = 1, trim = TRUE, scale = "width", width = 0.8,
        position = position_dodge(width = 0.9)
    ) +
    geom_jitter(
        size = 0.65, stroke = 0.4, shape = 21, alpha = 0.6,
        position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2)
    ) +
    stat_summary(
        fun = mean, geom = "point", shape = 8, color = "black", stroke = 0.85, size = 1,
        position = position_dodge(width = 0.9)
    ) +
    theme_Publication() +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    ylab("Expression\n(logcounts)") +
    xlab("Cell Type") +
    scale_color_manual(values = c(color_mapping[1], color_mapping[4])) +
    scale_fill_manual(values = alpha(c(color_mapping[1], color_mapping[4]), 0.3)) +
    ggtitle(gene) +
    NoLegend() 

ggsave(
    filename = here("scRNAseq","plots", "sup", "EV4C_Cph_expression.pdf"),
    plot = p,
    height = 4, width = 8, scale = 1.3
)
```

```{r}
sessionInfo()
```