---
title: "Supp Figure 4 MELD vs conventional DGE"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


## Introduction
Compare DGE results using MELD with the conventional pseudobulk approach

```{r load libraries}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)

# source plotting theme
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```



## compare between MELD and conventional approach:
```{r}
# check correlation between this and the "conventional approach"
conventional_Progenitor <- fread(here("output", "differential_expression","pseudobulk_coarse","Progenitor","edgeR_diff_expr.tsv"), data.table = F)%>% 
    mutate(approach = "conventional")

meld_Progenitor <- fread(here("output", "differential_expression","pseudobulk_coarse_meld","Progenitor","edgeR_diff_expr.tsv"), data.table = F)%>% 
    mutate(approach = "meld")

# combine all dataframes: 
combined_result <- rbind(
    conventional_Progenitor,
    meld_Progenitor
) %>% 
    tidyr::unite(., col="ID", c(celltype, approach))

logFC_df <- combined_result %>%
  select(gene, ID, logFC) %>%
  pivot_wider(names_from = ID, values_from = logFC, names_prefix = "logFC_")


# F statistic plots
celltypes <- c("Progenitor")


# LFC plot
lfc_plots <- lapply(celltypes, function(celltype){
    meld_col_string <- str_interp("logFC_${celltype}_meld")
    conventional_col_string <- str_interp("logFC_${celltype}_conventional")
    data <- logFC_df %>% select(contains(celltype)) %>% tidyr::drop_na()
    # Linear model
    model <- lm(as.formula(paste(meld_col_string, "~", conventional_col_string)), data = data)
    
    # Summary of the model to get the R^2 value
    summary_model <- summary(model)
    r_squared <- summary_model$r.squared
    
    ggplot(data,
           aes(x=!!sym(conventional_col_string), y=!!sym(meld_col_string)))+
        geom_point(shape=21, fill="black", alpha=0.3,color="black")+
        theme_Publication()+
        geom_smooth(method="lm", color="#0000ff")+
        ggtitle(celltype)+
        xlab("logFC\nconventional approach")+
        ylab("logFC\nMELD approach")+ 
        annotate("text", x = min(data[, conventional_col_string]), y = max(data[, meld_col_string]), 
                 label = paste("R² = ", round(r_squared, 3)), hjust = 0, vjust = 1, size = 4.5)
        
})


ggsave(
        filename = here("scRNAseq","plots", "sup", "ExtFig4A_MELD_vs_conventional.pdf"),
       plot=lfc_plots[[1]], width=4, height=3.5, scale = 1.2)


```

```{r}
sessionInfo()
```

