---
title: "Supp Fig 9 Compare DEG notchRNAi and notchKO"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```



```{r load libraries}
library(tidyverse)
library(Seurat)
library(patchwork)
library(here)
library(data.table)
library(VennDiagram)
library(RColorBrewer)

# source plotting theme
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


```{r}
notchRNAi <- fread(here("output", "differential_expression", "FindMarkers_MAST", "ISC_EEP_EB", "NotchRNAi_vs_ctrl_ISC_EEP_EB_MAST.tsv"), data.table=F)
notchKO <- fread(here("output", "differential_expression", "pseudobulk_coarse_meld", "Progenitor", "edgeR_diff_expr.tsv"), data.table=F)

combined <- inner_join(notchKO, 
                      notchRNAi,
                      by = c("gene"),
                      suffix = c("KO", "RNAi"))


p <- ggplot(combined, aes(logFC, avg_log2FC))+
    geom_vline(xintercept = 0, linetype="dashed", color="grey")+
    geom_hline(yintercept = 0, linetype="dashed", color="grey")+
    geom_point(size=0.5, shape=21, alpha=0.9, stroke=0.7)+
    xlab("logFC Notch KO")+
    ylab("logFC Notch RNAi")+
    theme_Publication()+
    geom_smooth(method= "lm", linewidth=0.8)+
    ggtitle("Progenitor Population")


# Calculate the R² value
model <- lm(logFC ~ avg_log2FC, data = combined)
r_squared <- summary(model)$r.squared

# Annotate the plot with the R² value
p <- p + annotate("text", x = min(combined$logFC), y = max(combined$avg_log2FC), 
             label = paste("R =", round(r_squared ^ 0.5, 2)), 
             hjust = 0, vjust = 1, size = 5, color = "black")

p <- p + annotate("text", x = min(combined$logFC), y = max(combined$avg_log2FC)-0.2, 
             label = "p = <2e-16", 
             hjust = 0, vjust = 1, size = 5, color = "black")

p

ggsave(
    plot = p,
    filename = here::here("scRNAseq", "plots", "sup", "ExtFig9C_NotchRNAi_vs_NotchKO.pdf"),
    width=4,height=3.5,scale = 1.5
    )


```



```{r}
sessionInfo()
```

















