---
title: "Supp Figure 5 Cph expression"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


```{r}
# load the integrated dataset
integrated <- readRDS(here("output", "Ctrl_NotchKO_integrated_scent.rds"))
integrated <- integrated[, !integrated$celltype_manual %in% c("MT", "unk", "unk2")]
integrated$celltype_manual <- ifelse(integrated$high_res_annotation == "EEP", "EEP", integrated$celltype_manual)

integrated$celltype_manual <- factor(integrated$celltype_manual,
    levels = c("ISC", "EEP", "EB", "dEC", "daEC", "aEC", "mEC", "Copper", "LFC", "pEC", "EE")
)
```


```{r}
p <- FetchData(integrated, c("CG9650", "perturbation", "celltype_manual")) %>%
    mutate(dummy = ifelse(perturbation == "ctrl", "X", "Z")) %>% # necessary to color the violines black...
    rownames_to_column("id") %>%
    pivot_longer(-c(id, perturbation, celltype_manual, dummy)) %>%
    ggplot(., aes(x = celltype_manual, y = value, color = perturbation, fill = perturbation)) +
    geom_point(size = 0.65, stroke = 0.4, shape = 21, position = position_jitterdodge(jitter.width = 0.3)) +
    geom_violin(
        mapping = aes(x = celltype_manual, y = value, color = dummy), inherit.aes = F,
        adjust = 1, trim = TRUE, fill = NA,
        scale = "width", show.legend = F,
        width = 0.72 # adjust width so the violin does not stick out too much
    ) +
    theme_Publication_side_legend() +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    stat_summary(
        fun = mean, geom = "point", shape = 8, color = "black", stroke = 0.85, show.legend = F,
        aes(group = perturbation), position = position_dodge2(width = 0.72)
    ) +
    ylab("Expression\n(logcounts)") +
    scale_color_manual(values = c(color_mapping[1], color_mapping[4], "black", "black")) +
    scale_fill_manual(values = alpha(c(color_mapping[1], color_mapping[4]), 0.3))


ggsave(
    plot = p,
    filename = here("plots", "sup", "Fig5_cph_expr.pdf"),
    width = 6,
    height = 2.5,
    scale = 1.7
)
```

