---
title: "Figure 4 Highlight coexpression of sc and Cph"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)

# source plotting theme
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


```{r}
seurat <- readRDS(here("output", "Ctrl_NotchKO_integrated_scent.rds"))

seurat@meta.data$expression_status <- case_when(
    (seurat@assays$RNA@counts["sc", ] > 0 & seurat@assays$RNA@counts["CG9650", ] > 0) ~ "sc+cph",
    seurat@assays$RNA@counts["sc", ] > 0 ~ "sc",
    seurat@assays$RNA@counts["CG9650", ] > 0 ~ "Cph",
    T ~ "neg."
)

seurat@meta.data$expression_status <- factor(seurat@meta.data$expression_status,
    levels = c("neg.", "Cph", "sc", "sc+cph")
)

# Create the DimPlot using ggplot2 functions to respect the order
umap_plot <- function(data, feature, dim_reduction = "umap", ...) {
    if (n_distinct(data[[feature]]) > 20) {
        print("Assuming the feature of interest is numeric")
        data[[feature]] <- as.numeric(data[[feature]])
    }
    stopifnot(all(rownames(embedding_df) == rownames(data)))
    data <- cbind(data, embedding_df)
    embedding_colnames <- colnames(data)[(ncol(data) - 1):ncol(data)]
    p <- ggplot(data, aes(!!sym(embedding_colnames[[1]]),
        !!sym(embedding_colnames[[2]]),
        color = !!sym(feature), size = !!sym(feature)
    )) +
        geom_point(...)
    if (n_distinct(data[[feature]]) < 20) {
        p <- p
    }
    return(p)
}

embedding_df <- Embeddings(seurat, "umap")
data <- FetchData(seurat, "expression_status", )
data <- data %>% arrange(factor(expression_status, levels = c("neg.", "Cph", "sc", "sc+cph")))
plot_data <- left_join(
    data %>% data.frame() %>% rownames_to_column("cellid"),
    embedding_df %>% data.frame() %>% rownames_to_column("cellid"),
)


p <- ggplot(plot_data, aes(x = UMAP_1, y = UMAP_2, color = expression_status, size = expression_status)) +
    geom_point(shape = 19, stroke = 0.25) +
    guides(color = guide_legend(override.aes = list(size = 1.3))) +
    scale_color_manual(values = c("lightgrey", "green", "red", "orange")) +
    scale_size_manual(values = c(0.05, 0.05, 0.05, 0.2)) + # highlight cells that express both
    small_axis("UMAP ") +
    scale_y_reverse() +
    scale_x_reverse() +
    theme(legend.title = element_blank())


ggsave(
    plot = p,
    filename = here("scRNAseq","plots", "sup", "ExtFig5B_Cph_expression.pdf"),
    width = 6,
    height = 2.5,
    scale = 1.7
)
```


```{r}
sessionInfo()
```



