---
title: "Figure 5"
author: "Erica Valentini"
date: "2024-09-05"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
    smooth_scroll: yes
  pdf_document: default
  number_sections: no
  highlight: tango
  theme: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE, cache = FALSE)
```

**Last modified:**
```{r}
print(date())
```

# Load packages and data

```{r load}

library(tidyverse)
library(UpSetR)
library(ggrepel)
library(Seurat)
library(ggpubr)
library(fgsea)
library(cowplot)
library(viridis)
library(ggalluvial)
library(ggplotify)

MAST_diff_expr_NotchCphRNAi_ISC_EEP <- read_tsv("../raw_data/MAST_diff_expr_NotchCphRNAi_Progenitor_ISC_EEP.tsv")
MAST_diff_expr_NotchRNAi_ISC_EEP <- read_tsv("../raw_data/MAST_diff_expr_NotchRNAi_Progenitor_ISC_EEP.tsv")

notch_cph_rnai <- readRDS("../raw_data/NotchCphRNAi.rds")
notch_rnai <- readRDS("../raw_data/NotchRNAi.rds")
control <- readRDS("../raw_data/ctrlRNAi_new.rds")
integrated <- readRDS("../raw_data/integrated.rds")

interesting_genes <- c("E(spl)malpha-BFM", "klu", "Dl", "Swim", "E(spl)mbeta-HLH", "Myc", "spdo", "sli", "crol", "endos", "arm", "msi", "Non1", "mnb", "sima", "Mad", "path", "Egfr", "mira", "EcR", "N", "mip40", "CycA", "InR", "Dp", "esg", "kuz", "kibra", "Cdc7", "grp", "Pdi", "Cph", "sc")
```


## Merge tables

```{r merge}

differentially_expressed_genes <- bind_rows(MAST_diff_expr_NotchCphRNAi_ISC_EEP, MAST_diff_expr_NotchRNAi_ISC_EEP)

#Rename CG9650 to Cph
differentially_expressed_genes <- differentially_expressed_genes %>% mutate(gene = ifelse(gene == "CG9650", "Cph", gene))

```

# Figure 5B

## Prepare data

```{r celltypes}

cell_types <- control@meta.data %>% 
  group_by(Sample, high_res_annotation) %>% 
  tally() %>% 
  mutate(condition = "control") %>% 
  bind_rows(notch_rnai@meta.data %>% 
              group_by(Sample, high_res_annotation) %>% 
              tally() %>% 
              mutate(condition = "notch_rnai")) %>% 
  bind_rows(notch_cph_rnai@meta.data %>% 
              group_by(Sample,celltype_manual) %>% 
              tally() %>% 
              mutate(condition = "notch_cph_rnai") %>% 
              dplyr::rename(high_res_annotation = celltype_manual)) %>% 
  ungroup()

# Rename specific AstC-EE, Tk-EE and classIII-EE to EE
EE_list <- c("AstC-EE", "Tk-EE", "classIII-EE")

cell_types <- cell_types %>% 
  mutate(high_res_annotation = ifelse(high_res_annotation %in% EE_list, "EE", high_res_annotation))

```

## Alluvial plot

```{r celltypes_alluvial}

celltype_colors = c("#d3534d", "#f8adb0", "#b388bd", "#197383", "#4e9acb", "#7bcfe2", "#e2cb88", "#c6b92f", "#218d44", "#81c579", "#ea9e59", "#585858")

celltype_order = c("ISC", "EEP", "EB", "dEC", "daEC", "aEC", "mEC", "Copper", "LFC", "pEC", "EE", "MT")

names(celltype_colors) <- celltype_order

cell_types %>%
  group_by(condition, high_res_annotation) %>% 
  summarise(n_cells = sum(n)) %>%  
  left_join(cell_types %>% group_by(condition) %>% summarise(total_cells = sum(n))) %>%
  mutate(cell_percentage = round((n_cells/total_cells)*100, digits = 1)) %>% 
  ungroup() %>% 
  select(condition, high_res_annotation, cell_percentage) %>% 
  mutate(condition = factor(condition, levels = c("notch_rnai", "control", "notch_cph_rnai"))) %>% 
  ggplot(aes(x=condition, y=cell_percentage, alluvium = high_res_annotation, stratum = high_res_annotation, fill = high_res_annotation)) +
  geom_flow(stat = "alluvium", lode.guidance = "frontback", color="darkgray") +
  geom_stratum() +
  scale_fill_manual(values = celltype_colors) +
  ggtitle("Percentage number of cells") +
  theme_cowplot()

ggsave(filename = "../Graphics/5B_alluvial_plot.pdf", device = "pdf")

```

# Figure 5C

```{r combined_volcano_genes, fig.width=16, fig.height=8}

log2fc_threshold = 0
pvalue_threshold = 0.05

# Excluded genes from plot:

differentially_expressed_genes %>% filter(logFC < -2)

differentially_expressed_genes %>% 
  mutate(condition = factor(condition, levels = c("NotchRNAi", "NotchCphRNAi"))) %>% 
    mutate(is_interesting = ifelse(
      p_adj < pvalue_threshold &
      gene %in% interesting_genes, "interesting gene", "not interesting gene")
    ) %>% 
    mutate(regulated = case_when(
     logFC < 0 & p_adj < pvalue_threshold ~ "downregulated",
     logFC > 0 & p_adj < pvalue_threshold ~ "upregulated",
     .default = "not significant"
    )) %>% 
    mutate(color = case_when(
      is_interesting == "interesting gene" ~ "interesting",
      regulated == "downregulated" ~ "downregulated not interesting",
      regulated == "upregulated" ~ "upregulated not interesting", 
      regulated == "not significant" ~ "not significant"
    )) %>% 
    arrange(desc(is_interesting)) %>% 
    ggplot(aes(x=logFC, y=-log10(p_adj), label = case_when(
      gene %in% interesting_genes & p_adj < pvalue_threshold ~ gene,
      .default = ""))) + 
    geom_point(aes(fill = regulated, colour = color, ), shape = 21, alpha = 0.7) + 
    scale_fill_manual(values = c("#629dff","gray", "#f7766d")) +
    scale_color_manual(values = c("#629dff","black", "gray", "#f7766d")) +
    geom_vline(xintercept = 0) +
    geom_text_repel(min.segment.length = 0, max.overlaps = Inf) +
    geom_hline(yintercept = -log10(pvalue_threshold)) +
    facet_wrap(facets = vars(condition), ncol = 2) +
    xlim(-2,2) +
    theme_cowplot()

ggsave(filename = "../Graphics/5C_volcano_plot.pdf", device = "pdf")

```

# Figure 5D

```{r upsetr}

upregulated_notchRNAi <- differentially_expressed_genes %>% filter(logFC > log2fc_threshold, p_adj < pvalue_threshold, condition == "NotchRNAi") %>% pull(gene)
downregulated_notchRNAi <- differentially_expressed_genes %>% filter(logFC <  log2fc_threshold, p_adj < pvalue_threshold, condition == "NotchRNAi") %>% pull(gene)
upregulated_notchCphRNAi <- differentially_expressed_genes %>% filter(logFC > log2fc_threshold, p_adj < pvalue_threshold, condition == "NotchCphRNAi") %>% pull(gene)
downregulated_notchCphRNAi <- differentially_expressed_genes %>% filter(logFC <  log2fc_threshold, p_adj < pvalue_threshold, condition == "NotchCphRNAi") %>% pull(gene)

listInput <- list(up_notchRNAi = upregulated_notchRNAi, down_notchRNAi = downregulated_notchRNAi, up_notchCphRNAi = upregulated_notchCphRNAi, down_notchCphRNAi = downregulated_notchCphRNAi)

for (element in seq(1:length(listInput))) {
  print(paste0(names(listInput)[[element]],": ", length(listInput[[element]])))
}

upset_plot <- upset(fromList(listInput), set_size.show = TRUE, order.by = "freq")

upset_plot

ggsave(plot = ggplotify::as.ggplot(upset_plot), filename = "../Graphics/5D_upset_plot.pdf", device = "pdf")

```

# Figure 5E

```{r FC correlation, fig.}


differentially_expressed_genes %>% 
  filter(condition == "NotchCphRNAi", p_adj < pvalue_threshold) %>% 
  inner_join(differentially_expressed_genes %>% filter(condition == "NotchRNAi", p_adj < pvalue_threshold), by = "gene", suffix = c(".notch.cph", ".notch")) %>% 
  mutate(is_interesting = ifelse(gene %in% interesting_genes, "interesting", "not interesting")) %>% 
  arrange(desc(is_interesting)) %>% 
  ggscatter(x="logFC.notch", 
            y = "logFC.notch.cph", 
            color = "is_interesting",
            legend = "none",
            add = "reg.line", 
            conf.int = TRUE, 
            palette = c("red", "gray10"), 
            add.params = list(color = "blue", fill="lightgray"), 
            alpha = 0.7) +
    geom_rug(side = "bi", aes(color = is_interesting), palette = c("red", "gray10")) +
    stat_cor(method = "pearson", label.y.npc = "bottom") +
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_vline(xintercept = 0, linetype = "dashed") +
    geom_text_repel(aes(label = if_else(gene %in% interesting_genes, gene, "")), max.overlaps = Inf, size=5, box.padding = 0.5)

ggsave(filename = "../Graphics/5E_correlation_plot.pdf", device = "pdf")

```


# Figure 5F

## Do the GSEA analysis

```{r fgsea_hallmark, fig.height=10, fig.width=8}

gene_sets <- readRDS("../raw_data/gene_sets.rds")

#format the gene set for fgsea
hallmark_list = gene_sets$hallmark %>% split(f = .$pathway_name, x = .$symbol)

rank_notch_cph <- differentially_expressed_genes %>% 
  filter(condition == "NotchCphRNAi") %>% 
    select(gene, logFC, p_adj) %>% 
    mutate(stat = sign(logFC)*-log10(p_adj)) %>% 
    select(gene, stat) %>% 
    deframe()

fgsea_notch_cph_hm <- fgsea(pathway = hallmark_list, stats = rank_notch_cph)

topPathwaysUp <- fgsea_notch_cph_hm[ES > 0][head(order(pval), n=15), pathway]
topPathwaysDown <- fgsea_notch_cph_hm[ES < 0][head(order(pval), n=15), pathway]
topPathways_notch_cph <- c(topPathwaysUp, rev(topPathwaysDown))

rank_notch <- differentially_expressed_genes %>% 
  filter(condition == "NotchRNAi") %>% 
    select(gene, logFC, p_adj) %>% 
    mutate(stat = sign(logFC)*-log10(p_adj)) %>% 
    select(gene, stat) %>% 
    deframe()

fgsea_notch_hm <- fgsea(pathway = hallmark_list, stats = rank_notch)

topPathwaysUp <- fgsea_notch_hm[ES > 0][head(order(pval), n=15), pathway]
topPathwaysDown <- fgsea_notch_hm[ES < 0][head(order(pval), n=15), pathway]
topPathways_notch <- c(topPathwaysUp, rev(topPathwaysDown))

hm_pathways_in_common <- intersect(fgsea_notch_hm %>% 
                                     arrange(pval, abs(NES)) %>% 
                                     filter(padj < 0.25) %>%
                                     pull(pathway), 
                                   fgsea_notch_cph_hm %>% 
                                     arrange(pval, abs(NES)) %>% 
                                     filter(padj < 0.25) %>% 
                                     pull(pathway))

```

## Compare GSEA hallmark

```{r compare_gsea_hm, fig.width=8}

fgsea_hm_tidy <- fgsea_notch_cph_hm %>% 
  as_tibble() %>% 
  mutate(condition = "NotchCph") %>% 
  bind_rows(fgsea_notch_hm %>% 
              as_tibble() %>% 
              mutate(condition = "Notch")) %>% 
  mutate(condition = factor(condition, levels = c("NotchCph", "Notch"))) %>% 
  filter(pathway %in% intersect(topPathways_notch, topPathways_notch_cph))

signed_pathway <- fgsea_hm_tidy %>% 
  distinct(pathway, NES) %>% 
  group_by(pathway) %>% 
  mutate(sign_NES = prod(sign(NES))) %>% 
  select(pathway, sign_NES) %>% 
  ungroup()

fgsea_hm_tidy %>% 
  filter(condition == "NotchCph") %>% 
  select(pathway, NES) %>% 
  arrange(NES) %>% 
  rownames_to_column(var="order") %>% 
  mutate(order = as.numeric(order)) %>% 
  select(order, pathway) %>% 
  left_join(fgsea_hm_tidy) %>% 
  left_join(signed_pathway) %>% 
  distinct() %>% 
  filter(sign_NES == -1) %>% 
    ggplot(aes(y=reorder(pathway, rev(order)), x=NES, color=padj, size = size)) + 
    geom_point() + 
    ylab("Hallmark Pathway") + 
    scale_color_viridis() +
    geom_vline(xintercept = 0) +
    facet_grid(cols = vars(condition)) +
    coord_cartesian(clip = "off") +
    theme_cowplot()

ggsave(filename = "../Graphics/5F_hm_gsea_dot_plot.pdf", device = "pdf")

```


# R session info

```{r}
sessionInfo()
```