---
title: "Supp Figure 3 MELD analysis"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```

```{r}
library(tidyverse)
library(patchwork)
library(data.table)
library(Seurat)
library(here)
library(ComplexHeatmap)
library(circlize)

# source plotting theme
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


## MELD
Check out the scripts in the `preprocessing_annotation/11_MELD` directory to see how the data which is loaded was generated.
```{r}
progenitors_integrated <- readRDS(here("output", "Ctrl_NotchKO_progenitors_integrated_meld.rds")) %>%
    RunUMAP(.,
        reduction = "pca", dims = 1:20,
        min.dist = 0.5,
        n.neighbors = 45,
        seed.use = 1,
        verbose = FALSE
    )

# start generating the plots
progenitors_integrated$high_res_annotation <- factor(progenitors_integrated$high_res_annotation,
    levels = c("ISC", "EEP", "EB")
)

celltype_umap <- new_dimplot(progenitors_integrated,
    feature = "high_res_annotation",
    shape = 19, size = 0.05, stroke = 0.3
) +
    ggtitle("Celltype") +
    small_axis("UMAP ", arrow_length = 20)+
    scale_color_manual(values = c(ISC, EEP, EB)) +
    theme(legend.title = element_blank())


perturbation_umap <- new_dimplot(progenitors_integrated,
    feature = "perturbation",
    shape = 19, size = 0.05, stroke = 0.3
) +
    scale_color_manual(values = c(color_mapping[1], color_mapping[4]), labels = c("Control", "Notch\nknockout")) +
    small_axis("UMAP ", arrow_length = 20)+
    ggtitle("Experimental label")

likelihood_umap <- new_dimplot(progenitors_integrated,
    feature = "N_likelihood",
    shape = 19, size = 0.05, stroke = 0.3
) +
    scale_color_gradient2(
        low = "#08519c",
        mid = "grey",
        high = "#a50f15",
        midpoint = 0.5,
        limits = c(0, 1),
        breaks = c(0, 1),
        labels = c("low", "high"),
        name = "Perturbation\nlikelihood"
    ) +
    small_axis("UMAP ", arrow_length = 20)+
    ggtitle("Likelihood of perturbation")


# get the cells barcodes that used to be notch, but are now assigned as "unperturbed"
reassigned_cells <- progenitors_integrated@meta.data[progenitors_integrated$VFC_2 == 0 & progenitors_integrated$perturbation == "notch", "Barcode_unique"]

plot_df <- FetchData(progenitors_integrated, c("VFC_2", "UMAP_1", "UMAP_2")) %>%
    mutate(VFC_2 = ifelse(rownames(.) %in% reassigned_cells, "unperturbed Notch", VFC_2)) %>%
    mutate(VFC_2 = factor(VFC_2, levels = c("0", "1", "unperturbed Notch"))) %>%
    arrange(VFC_2)

# shuffle the first 17228 rows. the last 1200 should stay the last
df1 <- plot_df %>% slice_head(., n = 17228)
df2 <- plot_df %>% slice_tail(., n = 1200)
identical(plot_df, rbind(df1, df2))
df1 <- df1 %>% sample_frac(1)
plot_df <- rbind(df1, df2)



prediction_umap <- plot_df %>%
    ggplot(., aes(UMAP_1, UMAP_2, color = VFC_2, size = VFC_2)) +
    geom_point(shape = 19, size = 0.05, stroke = 0.3) +
    scale_color_manual(values = c(color_mapping[1], color_mapping[4], "#25A017"), labels = c("unperturbed", "perturbed", "unperturbed Notch")) +
    scale_size_manual(values = c(0.2, 0.2, 0.2), labels = c("unperturbed", "perturbed", "unperturbed Notch")) +
    small_axis("UMAP ", arrow_length = 20)+
    ggtitle("MELD labels")+
    guides(color = guide_legend(override.aes = list(size = 1.3)))+
    theme(legend.title = element_blank())

combined <- wrap_plots(celltype_umap, perturbation_umap, likelihood_umap, prediction_umap) 

combined %>%
    ggsave(
        plot = .,
        filename = here("scRNAseq","plots", "sup", "ExtFig3A_MELD_eval.pdf"),
        width = 10,
        height = 7
    )
```


```{r}
sessionInfo()
```

