---
title: "Supp Figure 2 Marker gene expression"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```




```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```



```{r}
# load the integrated dataset
integrated <- readRDS(here("output", "Ctrl_NotchKO_integrated_scent.rds"))

integrated@meta.data$celltype_manual <- ifelse(grepl("unk", integrated@meta.data$celltype_manual), "unk", integrated$celltype_manual)
ctrl <- integrated[, integrated$perturbation == "ctrl" & ctrl$celltype_manual != "unk"]

genes <- c("path", "Vha100-4", "Npc2f", "dmGlut")

ctrl$celltype_manual <- factor(ctrl$celltype_manual,
    levels = c("ISC", "EB", "dEC", "daEC", "aEC", "mEC", "Copper", "LFC", "pEC", "EE", "MT")
)
```


```{r}
genes <- c("path", "Vha100-4", "Npc2f", "dmGlut")

p <- FetchData(ctrl, c(genes, "celltype_manual")) %>%
    rownames_to_column("id") %>%
    pivot_longer(-c(id, celltype_manual)) %>%
    mutate(name = factor(name, levels = c("path", "Vha100-4", "Npc2f", "dmGlut"))) %>%
    ggplot(., aes(x = celltype_manual, y = value, color = celltype_manual, fill = celltype_manual)) +
    geom_jitter(size = 0.65, stroke = 0.4, width = 0.2, shape = 21) +
    geom_violin(
        mapping = aes(x = celltype_manual, y = value), color = "black",
        adjust = 1, trim = TRUE, scale = "width", inherit.aes = F, fill = NA, width = 0.4 # adjust width so the violine does not stick out too much
    ) +
    theme_Publication() +
    theme(
        legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        axis.title.x = element_blank()
    ) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    stat_summary(
        fun = mean, geom = "point", shape = 8, color = "black", stroke = 0.85, show.legend = F,
        aes(group = celltype_manual), position = position_dodge(width = 0.9)
    ) +
    ylab("Expression (logcounts)") +
    scale_color_manual(values = sapply(levels(ctrl$celltype_manual), get)) +
    scale_fill_manual(values = alpha(sapply(levels(ctrl$celltype_manual), get), 0.3)) +
    facet_wrap(~name)


ggsave(
    plot = p,
    filename = here("plots", "sup", "Fig2_marker_gene_expression.pdf"),
    width = 4.8,
    height = 4,
    scale = 1.5
)
```





