---
title: "Figure 1 UMAP"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```




```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```



```{r}
# load the integrated dataset
integrated <- readRDS(here("output", "Ctrl_NotchKO_integrated_scent.rds"))

integrated@meta.data$celltype_manual <- ifelse(grepl("unk", integrated@meta.data$celltype_manual), "unk", integrated$celltype_manual)

integrated@meta.data$tmp_celltype <- case_when(
    integrated$high_res_annotation == "EEP" ~ "EEP",
    T ~ integrated$celltype_manual
)

ctrl <- integrated[, integrated$perturbation == "ctrl"]
notch <- integrated[, integrated$perturbation == "notch"]

ctrl$tmp_celltype <- factor(ctrl$tmp_celltype,
    levels = c("ISC", "EEP", "EB", "dEC", "daEC", "aEC", "mEC", "Copper", "LFC", "pEC", "EE", "MT", "unk")
)

notch$tmp_celltype <- factor(notch$tmp_celltype,
    levels = c("ISC", "EEP", "EB", "daEC", "aEC", "mEC", "Copper", "LFC", "pEC", "EE", "MT", "unk")
)
```

### Create the plot
```{r}
# this is just to get the legend
ctrl_umap <- DimPlot(ctrl,
    group.by = "tmp_celltype",
    pt.size = 0.00001,
    cols = c(ISC, EEP, EB, dEC, daEC, aEC, mEC, Copper, LFC, pEC, EE, MT, unk)
) +
    theme(
        plot.title = element_blank(), # element_text(hjust = 0.5, face="bold", size=11),
        legend.text = element_text(size = 8.5),
        legend.key.height = unit(0.45, "cm"),
        legend.key.width = unit(0.4, "cm")
    )

legend <- ggpubr::get_legend(ctrl_umap) %>%
    ggplotify::as.ggplot()


# here we create the actual plots
ctrl_umap <- new_dimplot(ctrl,
    feature = "tmp_celltype", size = 0.05,
    shape = 19,
    stroke = 0.25
) +
    scale_color_manual(values = c(ISC, EEP, EB, dEC, daEC, aEC, mEC, Copper, LFC, pEC, EE, MT, unk)) +
    small_axis("UMAP ", fontsize = 5, arrow_length = 17) +
    ggtitle("Control") +
    theme(
        plot.title = element_blank(), # element_text(hjust = 0.5, face="bold", size=11),
        legend.position = "none"
    ) +
    scale_y_reverse() +
    scale_x_reverse()



##############
# PLOT NOTCH #
##############
notch_umap <- new_dimplot(notch,
    feature = "tmp_celltype", size = 0.05,
    shape = 19,
    stroke = 0.25
) +
    scale_color_manual(values = c(ISC, EEP, EB, daEC, aEC, mEC, Copper, LFC, pEC, EE, MT, unk)) +
    small_axis("UMAP ", fontsize = 5, arrow_length = 17) +
    ggtitle("Notch-deficient") +
    theme(
        plot.title = element_blank(), # element_text(hjust = 0.5, face="bold", size=11),
        legend.position = "none"
    ) +
    scale_y_reverse() +
    scale_x_reverse()


combined_plots <- wrap_plots(ctrl_umap + NoLegend(),
    notch_umap,
    legend,
    nrow = 1
) +
    plot_layout(
        widths = c(1, 1, 0.3),
        heights = c(1, 1, 1)
    )

combined_plots %>%
    ggsave(
        plot = .,
        file = here("plots", "main", "Fig1_UMAPs.pdf"),
        width = 6.2,
        height = 3.3,
        units = "in",
    )
```

```{r}
sessionInfo()
```

