---
title: "Estimate the Cell cycle for the Notch KO data"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r load libraries}
library(here)
library(Seurat)
library(tidyverse)
library(patchwork)
library(gprofiler2)
# load custom functions
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```

## Introduction
Estimate the cell cycle phase that the cells are in using marker genes. 

```{r}
notch <- readRDS(here("output", "notchKO_seurat_integrated_annotated_high_res.rds"))

# Seurat comes with marker genes for the cell cycles in humans. we map them to drosophila
s_genes <- gorth(
    query = cc.genes.updated.2019$s.genes,
    source_organism = "hsapiens",
    target_organism = "dmelanogaster"
) %>%
    pull(ortholog_name)

g2m_genes <- gorth(
    query = cc.genes.updated.2019$g2m.genes,
    source_organism = "hsapiens",
    target_organism = "dmelanogaster"
) %>%
    pull(ortholog_name)



# run the scoring seperately for the replicates:
notch_split <- SplitObject(notch, split.by = "orig.ident")

notch_split <- lapply(setNames(names(notch_split), names(notch_split)), function(x) {
    print(x)
    tmp <- notch_split[[x]]
    tmp <- CellCycleScoring(tmp,
        g2m.features = g2m_genes,
        s.features = s_genes
    )
    return(tmp)
})

# make sure that the cell IDs are the same when transfering the metadata
stopifnot(all(Cells(notch) == lapply(notch_split, function(x) Cells(x)) %>%
    unlist() %>%
    unname()))

notch$S.Score <- sapply(notch_split, function(x) x$S.Score) %>%
    unlist() %>%
    unname()
notch$G2M.Score <- lapply(notch_split, function(x) x$G2M.Score) %>%
    unlist() %>%
    unname()
notch$Phase <- lapply(notch_split, function(x) x$Phase) %>%
    unlist() %>%
    unname()
saveRDS(notch, here("output", "notchKO_seurat_integrated_annotated_high_res_cellcycle.rds"))
```

# Visualize scoring
```{r}
# check the distribution of phases per celltype
phase_distribution <- notch@meta.data %>%
    group_by(Phase, celltype_manual) %>%
    tally() %>%
    left_join(., table(notch$celltype_manual) %>%
        enframe(name = "celltype_manual", value = "n_total")) %>%
    mutate(fraction = n / n_total) %>%
    mutate(Phase = factor(Phase, levels = c("G1", "S", "G2M"))) %>%
    dplyr::filter(celltype_manual != "unk2") %>%
    mutate(celltype_manual = factor(celltype_manual, levels = c(
        "aEC", "pEC", "Copper", "MT", "EE",
        "daEC", "EB", "ISC"
    )))

ggplot(phase_distribution, aes(x = Phase, y = fraction, fill = Phase)) +
    geom_col() +
    facet_wrap(~celltype_manual) +
    chameleon::scale_fill_chameleon() +
    theme_Publication() %+%
    theme(legend.position = "none") +
    ylab("Fraction of cells")
```


```{r}
sessionInfo()
```
















