---
title: "Estimate the Cell cycle for the NotchCphRNAi data"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```


```{r load libraries}
library(here)
library(Seurat)
library(tidyverse)
library(patchwork)
library(gprofiler2)

# load custom functions
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```

## Introduction
Estimate the cell cycle phase that the cells are in using marker genes. 

```{r}
NotchCphRNAi <- readRDS(here("output", "NotchCphRNAi_seurat_TX49_rep1_annotated.rds"))

# Seurat comes with marker genes for the cell cycles in humans. we map them to drosophila
s_genes <- gorth(
    query = cc.genes.updated.2019$s.genes,
    source_organism = "hsapiens",
    target_organism = "dmelanogaster"
) %>%
    pull(ortholog_name)


g2m_genes <- gorth(
    query = cc.genes.updated.2019$g2m.genes,
    source_organism = "hsapiens",
    target_organism = "dmelanogaster"
) %>%
    pull(ortholog_name)

res <- CellCycleScoring(NotchCphRNAi,
    g2m.features = g2m_genes,
    s.features = s_genes
)

NotchCphRNAi$S.Score <- res$S.Score
NotchCphRNAi$G2M.Score <- res$G2M.Score
NotchCphRNAi$Phase <- res$Phase
saveRDS(NotchCphRNAi, here("output", "NotchCphRNAi_seurat_TX49_rep1_annotated_cellcycle.rds"))
```

# Visualize scoring
```{r}
# check the distribution of phases per celltype
phase_distribution <- NotchCphRNAi@meta.data %>%
    group_by(Phase, celltype_manual) %>%
    tally() %>%
    left_join(., table(NotchCphRNAi$celltype_manual) %>%
        enframe(name = "celltype_manual", value = "n_total")) %>%
    mutate(fraction = n / n_total) %>%
    mutate(Phase = factor(Phase, levels = c("G1", "S", "G2M")))


ggplot(phase_distribution, aes(x = Phase, y = fraction, fill = Phase)) +
    geom_col() +
    facet_wrap(~celltype_manual) +
    chameleon::scale_fill_chameleon() +
    theme_Publication() %+%
    theme(legend.position = "none") +
    ylab("Fraction of cells")
```


```{r}
sessionInfo()
```





