---
title: "Recluster the EE population to resolve finer substractures"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```

## Introduction

We select all cells that were assigned as EEs and recluster them to identify subtypes that are known in the literature. 

Also for the ctrl it does not seem to make a lot of sense to do a subclustering.

```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(circlize)
library(ComplexHeatmap)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```

```{r}
# load the annotated seurat object
ctrl <- readRDS(here("output", "ctrlRNAi_seurat_integrated_annotated.rds"))

# select EE cells
DefaultAssay(ctrl) <- "RNA"
EE_ctrl <- DietSeurat(ctrl, assays = "RNA")[, ctrl$celltype_manual == "EE"]
EE_ctrl@meta.data <- EE_ctrl@meta.data %>%
    dplyr::select(-contains("integrated"))


EE_ctrl_split <- SplitObject(EE_ctrl, split.by = "orig.ident")

EE_ctrl_split <- lapply(EE_ctrl_split, function(x) {
    x <- NormalizeData(x, normalization.method = "LogNormalize", scale.factor = 10000) %>%
        FindVariableFeatures(., selection.method = "vst", nfeatures = 3000)
    return(x)
})

# do seurat integration
features <- SelectIntegrationFeatures(object.list = EE_ctrl_split)

# find anchors between experiments
anchors <- FindIntegrationAnchors(
    object.list = EE_ctrl_split,
    anchor.features = features,
    k.filter = 30
)
EE_ctrl_integrated <- IntegrateData(
    anchorset = anchors,
    k.weight = 30
)


DefaultAssay(EE_ctrl_integrated) <- "integrated"
EE_ctrl_integrated <- run_seurat_steps(EE_ctrl_integrated, include_norm = F, include_leiden = F, include_louvain = T)
DefaultAssay(EE_ctrl_integrated) <- "RNA"
```



```{r}
# based on literature and flygut atlas
marker_table <- data.frame(
    gene = c(
        "Tk", "Dh31", "NPF",
        "AstA", "AstC", "CCHa1",
        "CCHa2", "Orcokinin",
        "esg", "hdc", "Dl"
    ),
    celltype = c(
        "gut     \nhormones", "gut     \nhormones", "gut     \nhormones",
        "gut     \nhormones", "gut     \nhormones", "gut     \nhormones",
        "gut     \nhormones", "gut     \nhormones",
        "stem-cell\nmarker", "stem-cell\nmarker", "stem-cell\nmarker"
    )
)

marker_table$celltype <- factor(marker_table$celltype, levels = unique(marker_table$celltype))

# draw heatmap
heatmap_ctrl <- marker_heatmap(
    seurat = EE_ctrl_integrated,
    markers = marker_table$gene,
    celltype = marker_table$celltype,
    group.by = "integrated_snn_res.1.3",
    cap_value = 3
)

# assign subtypes based on this heatmap:
EE_ctrl_integrated$EE_subtype <- case_when(
    EE_ctrl_integrated$integrated_snn_res.1.3 == 0 ~ "AstC-EE",
    EE_ctrl_integrated$integrated_snn_res.1.3 == 1 ~ "AstC-EE",
    EE_ctrl_integrated$integrated_snn_res.1.3 == 2 ~ "EEP",
    EE_ctrl_integrated$integrated_snn_res.1.3 == 3 ~ "AstC-EE",
    EE_ctrl_integrated$integrated_snn_res.1.3 == 4 ~ "Tk-EE",
    EE_ctrl_integrated$integrated_snn_res.1.3 == 5 ~ "AstC-EE"
)


DimPlot(EE_ctrl_integrated,
    group.by = "EE_subtype",
    label = T, reduction = "umap"
)
```

### Now add this information back to the "whole" seurat object
```{r}
ctrl@meta.data$Barcode_unique <- Cells(ctrl)
ctrl@meta.data <- ctrl@meta.data %>%
    left_join(., EE_ctrl_integrated@meta.data %>%
        rownames_to_column("Barcode_unique") %>%
        select(Barcode_unique, high_res_annotation = EE_subtype),
    by = "Barcode_unique"
    )
rownames(ctrl@meta.data) <- ctrl$Barcode_unique
ctrl@meta.data$high_res_annotation <- case_when(
    is.na(ctrl@meta.data$high_res_annotation) ~ ctrl@meta.data$celltype_manual,
    T ~ ctrl@meta.data$high_res_annotation
)
saveRDS(ctrl, here("output", "ctrlRNAi_seurat_integrated_annotated_high_res.rds"))
```


```{r}
sessionInfo()
```
















