---
title: "Recluster the EE population to resolve finer substructures"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

## Introduction
We select all cells that were assigned as EEs and recluster them to identify subtypes that are known in the literature. 

```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(circlize)
library(ComplexHeatmap)
library(here)


source(here("plot_theme.R"))
source(here("helper_functions.R"))
set.seed(123)
```

```{r}
# load the annotated seurat object
notch <- readRDS(here("output", "notchKO_seurat_integrated_annotated.rds"))

# select EE cells
DefaultAssay(notch) <- "RNA"
EE_notch <- DietSeurat(notch, assays = "RNA")[, notch$celltype_manual == "EE"]
EE_notch@meta.data <- EE_notch@meta.data %>%
    dplyr::select(-contains("integrated"))

EE_notch_split <- SplitObject(EE_notch, split.by = "orig.ident")

EE_notch_split <- lapply(EE_notch_split, function(x) {
    x <- NormalizeData(x, normalization.method = "LogNormalize", scale.factor = 10000) %>%
        FindVariableFeatures(., selection.method = "vst", nfeatures = 3000)
    return(x)
})

# do seurat integration
features <- SelectIntegrationFeatures(object.list = EE_notch_split)

# find anchors between experiments
anchors <- FindIntegrationAnchors(
    object.list = EE_notch_split,
    anchor.features = features
)

EE_notch_integrated <- IntegrateData(anchorset = anchors)

DefaultAssay(EE_notch_integrated) <- "integrated"
EE_notch_integrated <- run_seurat_steps(EE_notch_integrated, include_norm = F, include_leiden = F, include_louvain = T)
EE_notch_integrated <- RunUMAP(EE_notch_integrated,
    reduction = "pca",
    dims = 1:20,
    min.dist = 0.7,
    n.neighbors = 5
)
DefaultAssay(EE_notch_integrated) <- "RNA"
```



```{r}
# based on literature and flygut atlas
marker_table <- data.frame(
    gene = c(
        "Tk", "Dh31", "NPF",
        "AstA", "AstC", "CCHa1",
        "CCHa2", "Orcokinin",
        "esg", "hdc", "Dl"
    ),
    celltype = c(
        "gut     \nhormones", "gut     \nhormones", "gut     \nhormones",
        "gut     \nhormones", "gut     \nhormones", "gut     \nhormones",
        "gut     \nhormones", "gut     \nhormones",
        "stem-cell\nmarker", "stem-cell\nmarker", "stem-cell\nmarker"
    )
)

marker_table$celltype <- factor(marker_table$celltype, levels = unique(marker_table$celltype))

# draw heatmap
heatmap_notch <- marker_heatmap(
    seurat = EE_notch_integrated,
    markers = marker_table$gene,
    celltype = marker_table$celltype,
    group.by = "integrated_snn_res.1",
    cap_value = 3
)

# assign subtypes based on this heatmap:
EE_notch_integrated$EE_subtype <- case_when(
    EE_notch_integrated$integrated_snn_res.1 == 0 ~ "AstC-EE",
    EE_notch_integrated$integrated_snn_res.1 == 1 ~ "EEP",
    EE_notch_integrated$integrated_snn_res.1 == 2 ~ "EEP",
    EE_notch_integrated$integrated_snn_res.1 == 3 ~ "EEP",
    EE_notch_integrated$integrated_snn_res.1 == 4 ~ "EEP",
    EE_notch_integrated$integrated_snn_res.1 == 5 ~ "AstC-EE",
    EE_notch_integrated$integrated_snn_res.1 == 6 ~ "EEP",
    EE_notch_integrated$integrated_snn_res.1 == 7 ~ "AstC-EE",
    EE_notch_integrated$integrated_snn_res.1 == 8 ~ "AstC-EE",
    EE_notch_integrated$integrated_snn_res.1 == 9 ~ "AstC-EE",
    EE_notch_integrated$integrated_snn_res.1 == 10 ~ "classIII-EE",
    EE_notch_integrated$integrated_snn_res.1 == 11 ~ "AstC-EE",
    EE_notch_integrated$integrated_snn_res.1 == 12 ~ "AstC-EE",
    EE_notch_integrated$integrated_snn_res.1 == 13 ~ "classIII-EE",
    EE_notch_integrated$integrated_snn_res.1 == 14 ~ "AstC-EE",
    EE_notch_integrated$integrated_snn_res.1 == 15 ~ "Tk-EE",
    EE_notch_integrated$integrated_snn_res.1 == 16 ~ "AstC-EE",
    EE_notch_integrated$integrated_snn_res.1 == 17 ~ "EEP",
)
```


### Now add this information back to the "whole" seurat object
```{r}
notch@meta.data$Barcode_unique <- Cells(notch)
notch@meta.data <- notch@meta.data %>%
    left_join(., EE_notch_integrated@meta.data %>%
        rownames_to_column("Barcode_unique") %>%
        select(Barcode_unique, high_res_annotation = EE_subtype),
    by = "Barcode_unique"
    )
rownames(notch@meta.data) <- notch$Barcode_unique
notch@meta.data$high_res_annotation <- case_when(
    is.na(notch@meta.data$high_res_annotation) ~ notch@meta.data$celltype_manual,
    T ~ notch@meta.data$high_res_annotation
)
saveRDS(notch, here("output", "notchKO_seurat_integrated_annotated_high_res.rds"))
```



```{r}
sessionInfo()
```
















