---
title: "Recluster the EE population to resolve finer substractures"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(123)
```

## Introduction
We select all cells that were assigned as EEs and recluster them to identify subtypes that are known in the literature. 

SUBCLUSTERING DOESNT MAKE SENSE FOR THIS CONDITION, BECAUSE WE JUST HAVE 11 CELLS.

```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
library(circlize)
library(ComplexHeatmap)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```

```{r}
# load the annotated seurat object 
notch_cph <- readRDS(here("output", "NotchCphRNAi_seurat_TX49_rep1_annotated.rds"))

# select EE cells
DefaultAssay(notch_cph) <- "RNA"

# in this case, reclustering doesnt make sense because its just 11 cells.
EE_notch_cph <- notch_cph[,notch_cph$celltype_manual=="EE"]

dim(EE_notch_cph)
```



```{r}
sessionInfo()
```
















