---
title: "Celltype assignment for Ctrl done manually"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

## Introduction
Do celltype assignment.


```{r}
library(Seurat)
library(tidyverse)
library(SingleR)
library(patchwork)
library(circlize)
library(ComplexHeatmap)
library(here)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
set.seed(123)
```

```{r}
# load integrated ctrl dataset.
ctrl <- readRDS(here("output", "ctrlKO_seurat_integrated.rds"))

# currated table of marker genes based on the literature such as https://www.pnas.org/doi/10.1073/pnas.1916820117 or https://www.science.org/doi/10.1126/science.abk2432 or
# https://www.sciencedirect.com/science/article/pii/S2211124715006075
marker_table <- data.frame(
    gene = c(
        "betaTry", "epsilonTry", "alphaTry",
        "nub", "Myo31DF",
        "esg", "N", "E(spl)mbeta-HLH", "klu",
        "Dl",
        "Vha100-4", "Vha16-1", "MtnC", "CG17109",
        "pros", "7B2", "IA-2",
        "PGRP-SC1a", "PGRP-SC1b", "Jon65Ai", "Jon65Aii", "Jon66Ci", "Jon66Cii",
        "lambdaTry", "LManVI", "iotaTry", "etaTry", "zetaTry",
        "thetaTry", "Npc2f",
        "Smvt", "ct"
    ),
    celltype = c(
        "aEC", "aEC", "aEC",
        "dEC", "dEC",
        "EB", "EB", "EB", "EB",
        "ISC",
        "Copper\ncells", "Copper\ncells", "Copper\ncells", "Copper\ncells",
        "EE", "EE", "EE",
        "LFC", "LFC", "LFC", "LFC", "LFC", "LFC", "LFC",
        "pEC", "pEC", "pEC", "pEC",
        "mEC", "mEC",
        "MT", "MT"
    )
)

Idents(ctrl) <- factor(ctrl$integrated_snn_res.1, levels = as.character(0:26))
p <- marker_heatmap(
    seurat = ctrl,
    markers = marker_table$gene,
    celltype = marker_table$celltype,
    group.by = "integrated_snn_res.1",
    cap_value = 3
)

p
# based on the heatmap  assign the labels
# add new label
ctrl$celltype_manual <- case_when(
    ctrl$integrated_snn_res.1 %in% c(0, 1, 2, 3, 10, 11, 23, 26) ~ "EB",
    ctrl$integrated_snn_res.1 %in% c(4, 5, 8, 9, 13, 14) ~ "aEC",
    ctrl$integrated_snn_res.1 %in% c(15, 16) ~ "EE",
    ctrl$integrated_snn_res.1 == 6 ~ "ISC",
    ctrl$integrated_snn_res.1 %in% c(7, 25) ~ "dEC",
    ctrl$integrated_snn_res.1 == 12 ~ "daEC",
    ctrl$integrated_snn_res.1 %in% c(17, 20) ~ "mEC",
    ctrl$integrated_snn_res.1 == 18 ~ "Copper",
    ctrl$integrated_snn_res.1 == 19 ~ "pEC",
    ctrl$integrated_snn_res.1 == 21 ~ "LFC",
    ctrl$integrated_snn_res.1 == 22 ~ "MT",
    ctrl$integrated_snn_res.1 == 24 ~ "unk",
    T ~ ctrl$integrated_snn_res.1
)
saveRDS(ctrl, here("output", "ctrlKO_seurat_integrated_annotated.rds"))
```

```{r, echo=T, message=T, error=T}
sessionInfo()
```
